<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>13.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <Authors>DatReki</Authors>
		<Description>A small library for thread safe collections</Description>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageReleaseNotes>Added "Find" method</PackageReleaseNotes>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>thread-safe collections ConcurrentObservableCollection ObservableCollection</PackageTags>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/DatReki/DR.ConcurrentCollections</RepositoryUrl>
		<VersionPrefix>1.0.1</VersionPrefix>
		<AssemblyVersion></AssemblyVersion>
		<FileVersion></FileVersion>
		<Title>$(AssemblyName)</Title>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <PackageReference Include="Backport.System.Threading.Lock" Version="3.1.5" />
    <PackageReference Include="System.Collections.Immutable" Version="10.0.1" />  
    <Using Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" Alias="Lock" Include="System.Threading.Lock" />
    <Using Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" Alias="Lock" Include="Backport.System.Threading.Lock" />
    <Using Alias="LockFactory" Include="Backport.System.Threading.LockFactory" />
  </ItemGroup>
</Project>
